# Generated by Django 5.0.1 on 2024-01-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentHasTag',
            new_name='Payment_Has_Tag',
        ),
    ]
