# Generated by Django 5.0.1 on 2024-02-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Transaction',
        ),
    ]
