# Generated by Django 5.0.1 on 2024-01-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
