# Generated by Django 5.0.1 on 2024-01-30 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1965, on_delete=django.db.models.deletion.CASCADE, to='finances.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
