# Generated by Django 5.0.1 on 2024-01-30 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_remove_payment_amount_payment_user_user_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_Has_Tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
